### ISSUE TITLE
Sending a message isn't quite the same thing as calling a method

### ISSUE THREAD

**Issue by ghost** [lazerwalker/fuckingblocksyntax.com#3]
Absolutely _love_ the crib sheet with the easily-remembered URL, but saying "As an argument to a method call" is not technically accurate for a page about Objective-C's syntactical vagaries.

**Comment by KyNorthstar** [comment]
I think the wording is fine for this site. If you change it to, say, "As an argument passed to a selector/message sent to a receiver", it would be too long and complex for the one-page site whose whole purpose is to say "Dangit I don't want to read through a bunch of technical docs just to figure out what the _goshdarn block syntax_ is" :P

**Comment by lazerwalker** [comment]
Even as message sending is great and conceptually important in Obj-C, Apple's own documentation describes these as "methods". I don't think this is going to mislead or misinform anyone :)

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/DefiningClasses/DefiningClasses.html)
