### ISSUE TITLE
Swift update

### ISSUE THREAD

**Issue by MartinJNash** [lazerwalker/fuckingblocksyntax.com#4]
Now that Swift is a thing, how about an update? ;)

**Comment by yas375** [comment]
Someone already made a similar page for Swift ;) http://fuckingswiftblocksyntax.com

**Comment by ReDetection** [comment]
and also http://fuckingclosuresyntax.com

**Comment by lazerwalker** [comment]
Yeah, I'm happy to let other folks pick up the banner for Swift and leave this for those who still need to remember Obj-C :)

**Comment by lazerwalker** [comment]
Yeah, I'm happy to let other folks pick up the banner for Swift and leave this for those who still need to remember Obj-C :)
